### ISSUE TITLE
问题留言

### ISSUE THREAD

**Issue by SkyShiS** [GeminiLight/sfc-deployment-algorithms#1]
作者您好，我想问一下：根目录下的main.py中
from RL.agent import Agent
from RL.env import PhysicalNetworkEnv, PNBatchEnv
是不是没有上传RL文件

**Comment by GeminiLight** [comment]
您好，目前repertory仅上传了GRC、MCTS、Random的实现，在algo文件下各算法的run.py文件可进行测试。
关于强化学习方法，我们尚未上传实现代码，main.py仅为早期实现demo版本，之后陆续开源我们团队的多种算法和添加其他算法。

**Comment by SkyShiS** [comment]
作者您好，问一下data/pn中的edges_data.csv中v_i和v_j是指代的什么
还有data\vn中的events_data.csv中的vn_id和type指代的是什么
events_data_2000_2-10_2-30_10_500.csv中events_data_后面的这些数字指的是什么
麻烦了

**Comment by GeminiLight** [comment]
v_i和v_j表示一条边的两个端点，events_data是事件文件，它表示vn的请求/离开事件的处理顺序信息，`type=1`表示请求，`type=0`则为离开，vn_id表示当前事件对应vn在vn_data中的索引。文件名称名称表示根据相应配置生成的处理顺序`events_data_file=f'events_data_{vns_num}_{min_length}-{max_length}_{min_request}-{max_request}_{new_arrival_rate}_{aver_lifetime}.csv'`
目前项目正在进行重构，预计重构后初始版本会在一月份末发布。该版本仅为部分功能实现单元的demo，且尚未提供具体的说明解释，给您造成的不便请谅解。

**Comment by SkyShiS** [comment]
作者您好，恭喜论文发表！想问一下代码什么时候发布，想学习一下

**Comment by GeminiLight** [comment]
现在在用算法做可视化系统参加一个比赛，为了避免麻烦和额外解释，打算在比赛评审阶段先不开源。不过一定会在ICC举行前开源
