### ISSUE TITLE
关于物理图的问题

### ISSUE THREAD

**Issue by HeYong2022dev** [GeminiLight/sfc-deployment-algorithms#2]
您好，请问一下您的物理图的节点和边的数据是怎么来的呀？是自己随机生成的还是在网上找的数据集呢？求指导

**Comment by GeminiLight** [comment]
是随机生成的，同这篇论文“Automatic VNE-A DRL approach with GCN. JSAC 2020“模拟设定相似

**Comment by HeYong2022dev** [comment]
您好，这篇论文我在google scholar上搜不到呢，能否给一个下载链接呢？

**Comment by GeminiLight** [comment]
不好意思，一些术语写了简写，应该是Automatic virtual network embedding: A deep reinforcement learning approach with graph convolutional networks，这里是[下载链接](https://ore.exeter.ac.uk/repository/bitstream/handle/10871/40799/Yan-JSAC-2020.pdf)

**Comment by HeYong2022dev** [comment]
好的，谢谢您
