### ISSUE TITLE
为什么actor_loss不收敛呢

### ISSUE THREAD

**Issue by swqsbssddqs** [GeminiLight/sfc-deployment-algorithms#8]
你好，作者大大，为什么actor_loss不收敛呢，全部参数都是virne里面默认的？
![image](https://github.com/GeminiLight/drl-sfcp/assets/71211938/fe198c7d-51bd-4b09-bfea-92104ea713ee)

**Comment by GeminiLight** [comment]
强化学习中actor loss和critic loss的趋势与agent收敛的关系并不紧密，更重要的是累积回报有没有提升、entroy_loss有没有下降。或许这两个指标可以更好的帮助你判断agent学习的情况。
